### ISSUE TITLE
Search string case sensitivity

### ISSUE THREAD

**Issue by effone** [nekolr/jquery-transfer#1]
Search is not always return the match.
Reason behind is the search system is currently case sensitive which should not be ...

**Comment by Sentence** [comment]
+1 for disable case sensitivity by default and enabling by option

**Comment by nekolr** [comment]
> 
> 
> +1 for disable case sensitivity by default and enabling by option

Thanks for your suggestion,  you can fork the project and then modify it. Currently the project is no longer maintained.

In addition, the group query is to query the items in the group.
