### ISSUE TITLE
Add Disabled items in list

### ISSUE THREAD

**Issue by farhad-dehghan** [nekolr/jquery-transfer#14]
Hi, would be very good to able add feature to consume "disabled" attribute like selected can be helpful for some case. for example if disabled key set in dataset,item can't selected with user. in both side, left and right box.
TNX

**Comment by nekolr** [comment]
Thanks for your suggestions, i will consider adding this feature

**Comment by nekolr** [comment]
> 
> 
> Hi, would be very good to able add feature to consume "disabled" attribute like selected can be helpful for some case. for example if disabled key set in dataset,item can't selected with user. in both side, left and right box.
> TNX

Thanks for your suggestions, i will consider adding this feature
