### ISSUE TITLE
html is not being escaped in checkbox labels

### ISSUE THREAD

**Issue by gmcalpin** [nekolr/jquery-transfer#21]
I have an item defined in my HTML where the label contains "greater than" and "less than" named entities:
var module_array = [
  ...
  {
    "module": "&amp;lt;De-serial&amp;gt; Serial Peripheral Interface . . . . . (&amp;lt;D&amp;gt;SPI) . . . . . (D_IP_DSPI_SYN)",
    "value": 68,
    "selected": true
  }
  ...
];

When the page loads, the item displays correctly in the right box.  When I transfer the item to the left box, it again displays correctly.  But if I then transfer the item back to the right box, the label does not display correctly.  The text inside of the '&lt;' and '&gt;' is not shown.

Changing line 963 of jquery.transfer.js from:
  html += self.generate_item(self.id, index, value, labelText, false);
to:
  html += self.generate_item(self.id, index, value, **$.escapeHtml(labelText)**, false);
seems to fix the problem.

Just to be clear, in my actual javascript code, the label is:
    "module": [LESS-THAN]De-serial[GREATER-THAN] Serial Peripheral Interface . . . . . ([LESS-THAN]D[GREATER-THAN]SPI) . . . . . (D_IP_DSPI_SYN)",
except instead of [LESS-THAN] and [GREATER-THAN], I have the appropriate named entities.

**Comment by nekolr** [comment]
Although it is not a good way, you can try to change the code on line 960：

`var labelText = self.$element.find(self.checkboxItemLabelClass).eq(i).text().replace("<", "&lt;").replace(">", "&gt;");`

**Comment by gmcalpin** [comment]
Thank you very much for your quick response!  Your suggestion works fine for what I need.  I'm in no position to judge whether or not it's a good way, but it's a "good enough" way for me.  Thanks!
