### ISSUE TITLE
batch wipe feature

### ISSUE THREAD

**Issue by hamzakaya** [nekolr/jquery-transfer#6]
I am currently trying to add features to select all items on the right side, do you have a suggestion? for bulk deletion

_Originally posted by @hamzakaya in https://github.com/nekolr/jquery-transfer/pull/5#issuecomment-566533428_

**Comment by nekolr** [comment]
I will check your code as soon as possible and give the modification

**Comment by nekolr** [comment]
By the way, the current code structure is too chaotic, and refactoring may be considered in the future

**Comment by nekolr** [comment]
> 
> 
> I am currently trying to add features to select all items on the right side, do you have a suggestion? for bulk deletion
> 
> _Originally posted by @hamzakaya in [#5 (comment)](https://github.com/nekolr/jquery-transfer/pull/5#issuecomment-566533428)_

The problem has been fixed :)

**Comment by hamzakaya** [comment]
Thank you.
There is an error in the search section, it does not search
I also want to make interface options. Bootstrap, Material-uI

**Comment by nekolr** [comment]
> 
> 
> Thank you.
> There is an error in the search section, it does not search
> I also want to make interface options. Bootstrap, Material-uI

Search function is normal, please merge code

**Comment by hamzakaya** [comment]
Yes merge did, actually the problem is as follows;
currently there is filtering by the first word, in case of multiple words there is a problem.

**Comment by nekolr** [comment]
> 
> 
> Yes merge did, actually the problem is as follows;
> currently there is filtering by the first word, in case of multiple words there is a problem.

You can try to enhance it if you need.
