### ISSUE TITLE
Is it possible to populate right column with some items from left column on init?

### ISSUE THREAD

**Issue by SergeyKoval** [nekolr/jquery-transfer#8]

**Comment by nekolr** [comment]
I don't know what you mean. Lazy load or need to append after initialization?

**Comment by nekolr** [comment]
> 
> 
> _No description provided._

It's ok. Please see: https://nekolr.github.io/jquery-transfer/

**Comment by zihjielitw** [comment]
他的意思是說，是否可以預設就已經有選擇好一些項目在右邊的欄位?
這也正是我想要問的

**Comment by nekolr** [comment]
> 
> 
> 他的意思是說，是否可以預設就已經有選擇好一些項目在右邊的欄位?
> 這也正是我想要問的

这个功能是有的，在 demo 中应该已经展示出来了。

demo：https://nekolr.github.io/jquery-transfer/

**Comment by zihjielitw** [comment]
> 
> 
> > 他的意思是說，是否可以預設就已經有選擇好一些項目在右邊的欄位?
> > 這也正是我想要問的
> 
> 这个功能是有的，在 demo 中应该已经展示出来了。
> 
> demo：https://nekolr.github.io/jquery-transfer/

是的，但是沒有實際的 Code 說明如何達到效果

**Comment by nekolr** [comment]
> 
> 
> > > 他的意思是說，是否可以預設就已經有選擇好一些項目在右邊的欄位?
> > > 這也正是我想要問的
> > 
> > 
> > 这个功能是有的，在 demo 中应该已经展示出来了。
> > demo：https://nekolr.github.io/jquery-transfer/
> 
> 是的，但是沒有實際的 Code 說明如何達到效果

demo 对应的就是项目中的 [index.html](https://github.com/nekolr/jquery-transfer/blob/master/index.html) 页面，里边有详细的例子。

**Comment by zihjielitw** [comment]
@SergeyKoval Please review index.html to get example.
@nekolr 感謝

**Comment by nekolr** [comment]
> 
> 
> @SergeyKoval Please review index.html to get example.
> @nekolr 感謝

不客气 :)
